### ISSUE TITLE
Adding feature of joining class from the link the teachers comments?

### ISSUE THREAD

**Issue by denppa** [plal99/Google-Meet-Bot#3]
Hello dev!

It is definitely a very nice thing you have put up here!

Though I want to know if you are able to add the feature in the script of clicking on the link below the class stream page title when the teacher comments it.

Since mine doesn't post them until the last minute, so maybe the script can reload the page until the link pops up under the title?

Please let me know if that is possible, since I don't know python myself.
And if it is, would you mind adding it to the script?

Thank you so much for putting this amazing automation script up!

**Comment by plal99** [comment]
It is actually possible. We can use the reload page option in selenium library to reload the page at a specific time interval till the link is visible in comment and then grab and go to the link. And this mode can be activated in telegram too. 

It would require lots of changes and time because, for debugging and testing we will have to use the platform where the teacher comments the link and I as an outsider cannot access that.

You can actually google how to reload page using selenium and find the text in the comment using selenium itself and I think it will be possible.

**Comment by denppa** [comment]
So I understand that it would take you time, but I believe you won't need to test it. 

Just write a line that reloads every 10 seconds on the class stream website that the person put up. Then at 2 minutes past actual start time, you can make the code click on the spot right below the title. No need to detect the link since it is always in the same place.

I don't care if I am 2 minutes late, the teachers aren't very punctual anyways and don't care. Or you can let people who wants it on time to set it to reload only once. Add a note in the READ.ME so people know where to change that value. 

And by same spot I mean it is literally under the title every single time:

[https://imgur.com/a/hYUOKvP](url)

So if the script can just selenium do this:

1. Go to google classroom stream instead of meet link at designated time

2. Reload page every 10 seconds for x12 times 
        -let people set the variable, from only reload once up to 12 (doesn't have to be convenient, just let them know which value on which line)
        -Even though I believe the link pops up regardless you reload the page or not, this is just to be safe.


3. Then make selenium click on the one spot opening the link for the meet

4. Execute rest of script as normally would, disable the mic and video and so on.
5. Leave when members fall below a certain number.

I have not learned python before so I don't know what I need to do in order to edit it for the code to work? Would you mind at least trying to implement the idea with the steps I find logical? Let me know if you think it can work or you changed it up a bit when you implemented what I said. Thanks!!

**Comment by denppa** [comment]
Too busy I suppose.

**Comment by plal99** [comment]
I'm having my exams right now. I'll get back to you after these hectic exams (Only after March 15, sorry!).

**Comment by plal99** [comment]
I need more data

I need images of how the link comes. It would be best if multiple screenshots are there from the loading of classroom page to the joining part of the meeting.

If links for different classes are in different folders in google classroom, then lots of work is there which I would not be able to do, because I cannot debug anything since it is your account. Sometimes I had to enter and leave out of a meeting like 30 times just to make some things work properly. Did you get what I mean? 

I could only make this program work after lots and lots of debugging and also because I was using my account to do all the debugging and I was mostly trying to tailor make it for my personal use.

Give me as much data as possible and I will try my best. Try to blur personal info (like passwords) if you are posting data in the comments.

Regards

**Comment by denppa** [comment]
I actually have a frame work up, but my knowledge on python and selenium is limited, so if you can collab with me on another platform for easier texting, per say discord would be great. You can let me know when you are open after the tests. Hit me up whenever though. 

I am currently in the middle of a bug and on the most basics of the script.

With features of launching browser, logging in, navigating to stream, and clicking on the meet link
Though some things like:
1.launch with default profile so I don't have to log in and will have access to extensions already installed
2.interaction with extensions
3.Respond to captions are my ultimate goal

But yeah, I have the framework, it just needs more work and knowledge.

Again, let me know whenever you are free. Maybe put your contact or something and then deleting it?

Wish you the best on the exams, dev!
